# Generated by Django 4.2.30 on 2026-06-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_churchowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Churches',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='attendance.church'),
        ),
        migrations.AddField(
            model_name='churchowner',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='attendance.church'),
        ),
        migrations.AddField(
            model_name='event',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.church'),
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='attendance.church'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('church', 'phone_number'), name='unique_church_member_phone'),
        ),
    ]
