# Generated by Django 5.2.15 on 2026-07-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_church_uuid_alter_event_uuid_alter_member_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchowner',
            name='church_name',
        ),
        migrations.AddField(
            model_name='churchowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
