# Generated by Django 5.2.15 on 2026-07-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_churchowner_church_name_churchowner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='is_student_church',
            field=models.BooleanField(default=False, help_text='Designates whether this church is a student fellowship/church.'),
        ),
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='e.g., 2026')),
                ('completion_date', models.DateField(help_text='The date when members of this class complete school.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_years', to='attendance.church')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='graduation_year',
            field=models.ForeignKey(blank=True, help_text="The student's graduation cohort.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='attendance.graduationyear'),
        ),
        migrations.AddConstraint(
            model_name='graduationyear',
            constraint=models.UniqueConstraint(fields=('church', 'year'), name='unique_church_graduation_year'),
        ),
    ]
