# Generated by Django 5.2.15 on 2026-07-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_church_is_student_church_graduationyear_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['completion_date']},
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='year',
            field=models.CharField(help_text='e.g., Year 1, Year 2, Class of 2028', max_length=100),
        ),
    ]
