# Generated by Django 5.2.15 on 2026-07-10 12:55

import django.db.models.deletion
from django.db import migrations, models


def migrate_departments(apps, schema_editor):
    Member = apps.get_model('attendance', 'Member')
    Department = apps.get_model('attendance', 'Department')
    for member in Member.objects.all():
        if member.old_department:
            if member.church:
                # get_or_create to safely create it if it doesn't exist yet
                dep, created = Department.objects.get_or_create(
                    church=member.church,
                    name=member.old_department
                )
                member.department = dep
                member.save()


def reverse_departments(apps, schema_editor):
    Member = apps.get_model('attendance', 'Member')
    for member in Member.objects.all():
        if member.department:
            member.old_department = member.department.name
            member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_graduationyear_options_and_more'),
    ]

    operations = [
        # 1. Create the Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department/ministry (e.g. Choir, Media)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='attendance.church')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_church_department'),
        ),
        
        # 2. Rename the old string field so we don't lose its data
        migrations.RenameField(
            model_name='member',
            old_name='department',
            new_name='old_department',
        ),

        # 3. Add the new ForeignKey field that will replace it
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, help_text="The member's department or ministry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='attendance.department'),
        ),

        # 4. Migrate the data safely
        migrations.RunPython(migrate_departments, reverse_code=reverse_departments),

        # 5. Drop the old string field
        migrations.RemoveField(
            model_name='member',
            name='old_department',
        ),
    ]
