# Generated by Django 5.2.15 on 2026-07-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_graduationyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department/ministry (e.g. Choir, Media)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='attendance.church')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, help_text="The member's department or ministry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='attendance.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_church_department'),
        ),
    ]
