# Generated by Django 5.2.15 on 2026-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_department_alter_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_visitor',
            field=models.BooleanField(default=False, help_text='Checked if the member is just visiting and not a permanent member.'),
        ),
    ]
