# Generated by Django 5.2.15 on 2026-07-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_member_is_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationyear',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='Mark this cohort as graduated to hide it from new registrations.'),
        ),
    ]
