# Generated by Django 5.2.15 on 2026-07-20 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_graduationyear_is_graduated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='graduation_year',
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Year 1, Year 2, Level 100', max_length=100)),
                ('sequence_order', models.PositiveIntegerField(help_text='Order of progression. Higher number means closer to graduation (e.g., 1, 2, 3).')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='attendance.church')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text="The student's current academic level.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='attendance.academiclevel'),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('emergency_phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('graduated_on', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='attendance.church')),
                ('department', models.ForeignKey(blank=True, help_text="The member's former department or ministry.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni', to='attendance.department')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduated_on', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='GraduationYear',
        ),
        migrations.AddConstraint(
            model_name='academiclevel',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_church_academic_level'),
        ),
        migrations.AddConstraint(
            model_name='academiclevel',
            constraint=models.UniqueConstraint(fields=('church', 'sequence_order'), name='unique_church_academic_sequence'),
        ),
    ]
