# Generated by Django 5.2.15 on 2026-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_member_graduation_year_academiclevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
